#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProcs=16

#-- Step 1: Generate and refine mesh
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication topoSet

#-- Step 2: Copy initial conditions
rm -rf 0
cp -r 0.orig 0

#-- Step 3: Split mesh into fluid/solid/heater regions
runApplication splitMeshRegions -cellZones -overwrite
rm -rf constant/polyMesh

#-- Step 4: Decompose and run in parallel
runApplication decomposePar -allRegions
mpirun -np $nProcs icoBoilingFoam -parallel > log.icoBoilingFoam 2>&1
runApplication reconstructPar -allRegions -latestTime

#------------------------------------------------------------------------------
