#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProcs=16

#-- Step 1: Generate mesh (fluid-only, no solid region)
runApplication blockMesh -region fluid

#-- Step 2: Copy initial conditions
rm -rf 0
cp -r orig.0 0

#-- Step 3: Decompose and run in parallel
runApplication decomposePar -region fluid
mpirun -np $nProcs icoBoilingFoam -parallel > log.icoBoilingFoam 2>&1
runApplication reconstructPar -region fluid -latestTime

#------------------------------------------------------------------------------
